name: adele
channels:
        - conda-forge 
dependencies:
        - python=3.8.5
        - matplotlib==3.3.2
        - mne==0.22.0
        - numpy==1.20.1
        - plotly==4.14.3
        - pandas==1.1.3
        - scikit-learn==0.23.2
        - pip
        - pip:
                - opencv-python==4.5.1.48
                - PyMuPDF # restricting to  1.18.8 results in "no module named frontend" (or can't coexist with fitz)
                - requests
